<?php

/** @var \AHT\CustomCheckout\Block\Template $block */
$order = $block->getOrder();
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Delivery Information')) ?></span>
        <div class="actions"><?= /* @noEscape */ $block->getEditLink(); ?></div>
    </div>
    <div class="admin__page-section-content">
        <p><span><label>Date : </label></span><?= $order->getDeliveryDate() ?></p>
        <p><span><label>Note : </label></span><?= $order->getDeliveryComment() ?></p>
    </div>
</section>